INSERT INTO wali_orang_tua (id_wali, status_wali, pekerjaan, username_wali) VALUES
('10', 'Orang Tua', 'Pegawai Negeri Sipil', 'hanigz'),
('11', 'Orang Tua', 'Pegawai Negeri Sipil', 'elipaarm'),
('12', 'Orang Tua', 'Wiraswasta', 'kaylaarm'),
('13', 'Orang Tua', 'Anggota DPD', 'oninilpd'),
('14', 'Orang Tua', 'Dokter', 'umayaala'), 
('15', 'Saudara', 'Wiraswasta', 'mitratu'),
('16', 'Orang Tua', 'Wiraswasta', 'galaknta'),
('17', 'Orang Tua', 'Pegawai Negeri Sipil', 'meliah'),
('18', 'Orang Tua', 'Anggota DPR-RI', 'salwalari'),
('19', 'Orang Tua', 'Wiraswasta', 'alikanaga'),
('110', 'Keponakan', 'Pensiunan', 'waniah'),
('111', 'Orang Tua', 'Wiraswasta', 'banasi'),
('112', 'Orang Tua', 'Wiraswasta', 'anited'),
('113', 'Orang Tua', 'Tentara Nasional Indonesia', 'galurip'),
('114', 'Orang Tua', 'Kepolisian RI', 'hanasi'),
('115', 'Orang Tua', 'Kepolisian RI', 'jokopriambodo'),
('116', 'Saudara', 'Kepolisian RI', 'agustantram'), 
('117', 'Orang Tua', 'Tentara Nasional Indonesia', 'sendangsejati'),
('118', 'Orang Tua', 'Tentara Nasional Indonesia', 'kurniawant'),
('119', 'Orang Tua', 'Dosen', 'bambangaji');